# Generated by Django 6.0.2 on 2026-02-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
