# Generated by Django 6.0.2 on 2026-02-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.profile')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='diagnostics.diagnosticresult')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'is_read', '-created_at'], name='notificatio_patient_95726b_idx')],
            },
        ),
    ]
