# Generated by Django 6.0.2 on 2026-02-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('brain_tumor', 'Brain Tumor Segmentation'), ('fracture', 'Fracture Detection'), ('pneumonia', 'Pneumonia Classification')], max_length=30)),
                ('verdict', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_created', to='accounts.profile')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='results_received', to='accounts.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', '-created_at'], name='diagnostics_patient_f9bcad_idx'), models.Index(fields=['model_type', '-created_at'], name='diagnostics_model_t_6d0152_idx')],
            },
        ),
    ]
