# Generated by Django 6.0.2 on 2026-03-04 16:34

import diagnostics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresult',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to=diagnostics.models.upload_input_to),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='output_png',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='output_png_content_type',
            field=models.CharField(default='image/png', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='output_png_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
