# Generated by Django 6.0.2 on 2026-03-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_personal_email'),
        ('diagnostics', '0002_diagnosticresult_input_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticresult',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('forwarded', 'Forwarded to Patient'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosticresult',
            name='verdict',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='diagnosticresult',
            index=models.Index(fields=['status', '-created_at'], name='diagnostics_status_e40d48_idx'),
        ),
    ]
